# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Inputs Workflow

on:
 workflow_dispatch:
    branches:
      - main
    inputs:
      version_bump_type:
        description: 'Version Bump Type (major, minor, patch)'
        required: true
        default: 'minor'
      version_metadata_path:
        description: 'Path to file containing Version string'
        required: true
        default: 'VERSION'
      generic_version_template:
        description: 'Go Template used for updating metadata file'
        required: true
        default: 'version := "%d.%d.%d"'
    
jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14']

    steps:
    - 
      uses: actions/checkout@v2

    - 
      run: |
        echo version_bump_type: ${{ github.event.inputs.version_bump_type }}
        echo version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
        echo generic_version_template: ${{ github.event.inputs.generic_version_template }}}

    - 
      name: Generic Version Bumpr
      id: semver
      uses: PackagrIO/action-bumpr-generic@v0.0.1
      with:
        version_bump_type: ${{ github.event.inputs.version_bump_type }}
        version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
        generic_version_template: ${{ github.event.inputs.generic_version_template }}

    - 
      run: echo version is ${{ steps.semver.outputs.release_version }}
